#!/bin/bash
# set openFoam environment
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Clear old IC
rm -rf 0

# run mesher
python3 hfdibrans_mesher.py

# create base mesh 
runApplication blockMesh

# copy IC
mkdir -p 0
cp -rf 0.org/* 0

# gen lambda field
runApplication createLambdaBFSV3 1.0 0.0013 0.01 0.0013

# get the solver application
application=`getApplication`

# run the application
runApplication $application

# run post processing
runApplication readAndWriteVelocity
runApplication readAndWriteTurbulenceFields epsilon
